### ISSUE TITLE
⚙️有些item是null的，也许做点处理好一点

### ISSUE THREAD

**Issue by jingming295** [BSTluo/koishi-plugin-nazrin-core#2]
```
2023-10-10 15:35:20 [W] app d:\CODE\iirose-bot\external\nazrin-core\src\pageHtmlMake.ts:14
                              <div class="content">${(item.name.length <= 15) ? item.name : item.name.substr(0,10) + "..." }</div>
                                                           ^

                        TypeError: Cannot read properties of null (reading 'name')
                            at null.<anonymous> (d:\CODE\iirose-bot\external\nazrin-core\src\pageHtmlMake.ts:14:36)
                            at Array.map (<anonymous>)
                            at null.pageMake (d:\CODE\iirose-bot\external\nazrin-core\src\pageHtmlMake.ts:12:22)
                            at null.<anonymous> (d:\CODE\iirose-bot\external\nazrin-core\src\index.ts:43:33)
                            at runMicrotasks (<anonymous>)
                            at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by BSTluo** [comment]
唔现在还有这个问题吗？）我明天修一下
